name: C application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install libncurses5-dev libncursesw5-dev libcurl4-openssl-dev
        python -m pip install --upgrade pip
        pip install meson ninja
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup meson build
      run: |
        meson setup build
    - name: Compile with meson
      run: |
        meson compile -C build
